apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default (include "leviticus.fullname" .) }}
  labels:
    {{- include "leviticus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.services }}
  {{- $svcName := .name }}
  {{- if .port }}
    - port: {{ .port }}
      targetPort: {{ $svcName }}
      protocol: TCP
      name: {{ $svcName }}
  {{- else if and .startPort .endPort }}
    {{- range $i := untilStep (.startPort | int) (add 1 .endPort | int) 1 }}
    - port: {{ $i }}
      targetPort: {{ printf "%s-%v" $svcName $i}}
      protocol: TCP
      name: {{ printf "%s-%v" $svcName $i}}
    {{- end }}
  {{- end }}
{{- end }}
  selector:
    {{- include "leviticus.selectorLabels" . | nindent 4 }}
